### ISSUE TITLE
jaque in annotation processor

### ISSUE THREAD

**Issue by vnesterovsky** [TrigerSoft/jaque#11]
Hello!

Sorry, that I'm abusing Issues forum. 
I'm going to suggest a feature request rather than to report an issue.

Did you think about running jaque as part of annotation processor?
If it's possible then expression tree can be used to generate some code at compile time (e.g. JPA expressions), or what ever other code or resource.

**Comment by kostat** [comment]
@vnesterovsky: Jaque was primarily designed for runtime, much like its spiritual parent LINQ. But of course it can be used in any place where there is a need to translate Lambda logic to something. Back to your comment, not sure I understand what new feature you suggest for jaque?

**Comment by vnesterovsky** [comment]
In contrast to LINQ Jaque builds expression tree at runtime, while LINQ does it at compile time.
So, my question was about this: did you look into directing of moving all that parsing at compilation (e.g. at annotation processing) stage. This way you could eliminate all byte code parsing dependencies, and could it make much lighter at runtime.

**Comment by kostat** [comment]
Well, there is nothing that prevents using jaque in the way you suggest. Jaque focuses on parsing the closure and building the expression trees. It looks like you talk about about some different project that might use Jaque in the backend.
