### ISSUE TITLE
Usage and applicability questions

### ISSUE THREAD

**Issue by akarnokd** [TrigerSoft/jaque#12]
I'd like to use the concept/approach of this library to have remote reactive operations (backed by RxJava/Reactive RPC) and I have the following questions:

  - Does JaQue support non-lambdas, such as anonymous inner classes or actual implementors of a particular functional interface?
  - Lambdas (and inner classes) may capture things that make no sense (or aren't available) on the other side. Is it possible to whitelist what the lambda body/method can do or is safe (such as System.currentTimeMillis())?
  - What would you suggest as the means to get the context information into the expression-tree to be run remotely? For example, instead of sending `Function<T, R>`, one should send `BiFunction<T, C, R>` where C is the type of the remotely available context object. This means the fluent API should be designed with the `BiFunction` as well (or the entire fluent API should carry around the context type C)?

**Comment by kostat** [comment]
* support non-lambdas: JaQue was implemented with .Net LINQ use cases in mind and made several assumptions. The major one in your context is that it assumes the ability to represent the method body as a binary tree, so for example switch or throw constructs are not supported. This is something that might be added, but will require a design phase (how the tree will look like etc). 
Behind the scenes Java creates classes for lambdas, but they are synthetic and at the moment JaQue will throw if the passed object is not synthetic.
* "Things" capturing: Once  the lambda is parsed, you get its body as a tree and "captured" things will be seen as ParameterExpression(s). It's fairly simple to traverse the tree and validate it. Potentially it can be plugged in into annotation processor and validated even in design time, but I'm not an expert in that area.
* Context: multi parameter lambdas idea sounds OK if type information is enough to get the context instance(s). The parameters will be parsed as ParameterExpression(s).
