### ISSUE TITLE
Can not parse contains method

### ISSUE THREAD

**Issue by hwy425** [TrigerSoft/jaque#15]
I pre-defined a list as below
```
List list = new ArrayList();
list.add(new Integer(1));
list.add(new Integer(2));
list.add(new Integer(3));
the i get an expression example : obj => list.contains(obj.Value)
```
Sorry, i means how can I convert this expression to sql statement  as below:

where value in (1,2,3)

**Comment by kostat** [comment]
Dup of #14. As I asked there - please provide a code snippet which reproduces the issue.
