### ISSUE TITLE
Assignability in the TypeConverter 2

### ISSUE THREAD

**Issue by CollinAlpert** [TrigerSoft/jaque#20]
Whenever linking Predicates with the `and` method, the constructor of `InvocationExpression` throws an `IllegalArgumentException`. Somewhere along the way, the `TypeConverter` tries to compare a `boolean` to an `int`. And this, of course, does not work.
Here's the code I was running:

```
SqlPredicate<Person> predicate1 = person -> person.getAge() > 18;
SqlPredicate<Person> predicate2 = person -> person.getFirstName() == "Bob";
LambdaExpression<SqlPredicate<Person>> lambdaExpression = LambdaExpression.parse(predicate1.and(predicate2));
```

The only difference between an `SqlPredicate<T>` and a `Predicate<T>` is that the `SqlPredicate<T>` is serialized.

**Comment by kostat** [comment]
Update: implementing higher level functions turned to be a bit tricky. I have a general case implementation, but need few more days to complete it.

**Comment by kostat** [comment]
There is still one very useful use case that fails - double (or greater) composition. Need to recurse while parsing lambda's captures.

**Comment by kostat** [comment]
Pushed a new <jaque-2.1.4> release to maven central
