### ISSUE TITLE
Method references

### ISSUE THREAD

**Issue by CollinAlpert** [TrigerSoft/jaque#26]
There seems to be an issue when using a method reference instead of a lambda expression.
Take the simplified class
```
public class Person {
    private int age;
    public boolean isAdult() {
        return age >= 18;
    }
}
```

when using it in a lambda, I don't use `person -> person.isAdult()` (in a Predicate), but `Person::isAdult`. This results in the exception: `java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0` in the `convertArguments` method of the `ExpressionMethodVisitor` class. When writing it as a lambda, it works fine.

**Comment by kostat** [comment]
Cannot repro on 2.2.0 release with this test (Serializable version works as well):

```java
public class Person1 {
	private int age;

	public boolean isAdult() {
		return age >= 18;
	}
}

@Test
public void testMethodRef2() throws Throwable {
	Predicate<Person1> pp = Person1::isAdult;

	LambdaExpression<Predicate<Person1>> parsed = LambdaExpression.parse(pp);
	Function<Object[], ?> le = parsed.compile();

	Person1 c = new Person1();

	assertEquals(pp.test(c), le.apply(new Object[] { c }));
}
```

Can you post the stack trace and the repro code?

**Comment by CollinAlpert** [comment]
I get the error when running this test:
```
SqlPredicate<Person> person = Person::isAdult;
SqlPredicate<Person> personAnd = person.and(x -> true);
LambdaExpression<SqlPredicate<Person>> lambda = LambdaExpression.parse(personAnd);
```
When declaring the `person` variable as a normal lambda, the error does not occur. Please also note I am running JDK 11. Don't know if that makes a difference.

I've also noticed that the `Predicate#and` method still causes some problems, although I can't quite pin point when yet. Will open an issue when I find out more.
