### ISSUE TITLE
Assignability in the TypeConverter 3

### ISSUE THREAD

**Issue by CollinAlpert** [TrigerSoft/jaque#27]
It seems I have found a concrete example for the issue with the `Predicate#and` method. When running this code:
```
long id = 1;
SqlPredicate<Person> personPredicate = person -> person.getId() == id;
SqlPredicate<Person> personSqlPredicateAnd = personPredicate.and(x -> true);
LambdaExpression<SqlPredicate<Person>> pred = LambdaExpression.parse(personSqlPredicateAnd);
```
I get the exception `java.lang.IllegalArgumentException: 0` which is thrown in the constructor of the `InvocationExpression` class. When using the `id` as a constant and not as a variable, the exception doesn't get thrown.

Again, I am using JDK 11 and don't know if that has something to do with anything.

**Comment by kostat** [comment]
Fixed by the fix for #26.
