### ISSUE TITLE
Inequality null comparisons

### ISSUE THREAD

**Issue by CollinAlpert** [TrigerSoft/jaque#31]
What about inequality comparisons with `null`? Any chance you could add an `ExpressionType.IsNotNull` just like `ExpressionType.NotEqual` exists for `ExpressionType.Equal`?
Right now, `person -> person.getName() != null;` gets evaluated to `!(Is Null)P0.getName()`. It is possible to evaluate that, but it's really dirty and probably also not very safe. Something like `(Is Not Null)P0.getName()` would be really great!

**Comment by kostat** [comment]
Will do

**Comment by CollinAlpert** [comment]
Thanks so much! Will there be a Maven release for this?

**Comment by kostat** [comment]
done
