### ISSUE TITLE
Java11 support

### ISSUE THREAD

**Issue by mojo2012** [TrigerSoft/jaque#33]
When building with java7 my integration test crashes with a `UnsupportedOperationException("This feature requires ASM7")`. Both `ExpressionClassVisitor` and `ExpressionMethodVisitor` are callign `super` with `ASM5` - this seems to be the reason. I tried fixing it by using `ASM7`, but unfuortunately the tests fail on my machine (even with unchanged sources).

Adding a check for the java version might be useful in that case?

With my little fix https://github.com/spot-next/spot-framework/blob/develop/spot-core/src/test/java/io/spotnext/test/persistence/QueryLanguageIT.java (`testLamdbaQuery`) works fine again under OpenJDK 11

**Comment by mojo2012** [comment]
Steps to reproduce:
1. checkout `https://github.com/spot-next/spot-framework` and switch to `develop`
2. Set `JAVA_HOME` to "jdk 11"
3. `mvn clean install`

The `testLambdaQuery` will fail with the above message complaining about `ASM7`. 

Look at the log: [mvn.log](https://github.com/TrigerSoft/jaque/files/2618831/mvn.log)

`jave -version` output:
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20181115_16 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dcd
OMR      - ea548a66
JCL      - d4455071ce based on jdk-11.0.1+13)
```

**Comment by mojo2012** [comment]
Abd when will the new release be available?

**Comment by kostat** [comment]
pushed to maven. Will be propagated in few hours
