### ISSUE TITLE
Compile errors in master

### ISSUE THREAD

**Issue by ErikNeudert** [TrigerSoft/jaque#38]
I checked out the project and had over 200 compile errors, mainly from missing getters.
I fixed them and would like to contribute, because I was looking forward to build such a framework for implementing a ORM.

**Comment by kostat** [comment]
@ErikNeudert : as you can see, the project successfully passes [Travis build](https://travis-ci.org/TrigerSoft/jaque), so there is no compile errors. I assume you did not configure lombok properly. But the question is why should you build it? If you want to implement an ORM, you should use JaQue as a dependency. Just note, that your project license is GPL compatible.
In any case I don't accept contributions, only bug reports.

**Comment by ErikNeudert** [comment]
Hello TrigerSoft,I didn't know about lombok, that was probably the cause for the compile errors.I wanted to build it to be able to debug and modify the code.As far as I understand the GPL, it is okay for me to modify the code, play around with it and share it in my own github.Would you be okay with that?Best Regards,ErikAm 05.04.2019 18:47 schrieb Konstantin Triger <notifications@github.com>:@ErikNeudert : as you can see, the project successfully passes Travis build, so there is no compile errors. I assume you did not configure lombok properly. But the question is why should you build it? If you want to implement an ORM, you should use JaQue as a dependency. Just note, that your project license is GPL compatible.
In any case I don't accept contributions, only bug reports.

**Comment by kostat** [comment]
You can see the meaning of GPL in the [GitHub GPL summary](https://github.com/TrigerSoft/jaque/blob/master/LICENSE). See permissions and conditions. In particular, one of the conditions is that your project will have the same (GPL) license.
