### ISSUE TITLE
Possible continuation

### ISSUE THREAD

**Issue by CollinAlpert** [TrigerSoft/jaque#39]
I saw that this project was discontinued. Is there any chance I can keep using it and keep it up to date myself? My library depends heavily on it and I can't migrate to the successor you've mentioned.

**Comment by kostat** [comment]
Hey Collin,

No, this project is discontinued. But your fork is yours :-)

Kosta

**Comment by CollinAlpert** [comment]
Hey, thanks for your reply! What I meant to ask, was, since this project is discontinued anyway, if I can now push my fork to Maven. I really need this project as a dependency in my other projects. It would be very nice if you could allow me to do so.

**Comment by kostat** [comment]
Of course.

Just make sure your artifact has a completely different name and group id
than mine. To eliminate any mistakes now or in the future.

Good luck,

Kosta
