### ISSUE TITLE
Jaque sources

### ISSUE THREAD

**Issue by Dan6667** [TrigerSoft/jaque#40]
Seems like email kostat@trigersoft.com isn't working and I haven't found other way to contact you, so excuse me for writing it here.
I know Jaque project is discontinued, but I would like to use it in my projects.
Current version only partially satisfies my needs and I want to fork from it (and I think I found some bugs there).
Apparently, I haven’t found sources at github (https://github.com/TrigerSoft/jaque/tree/master).
So, is there repository from where I can pull/fork?
Thanks in advance.

**Comment by kostat** [comment]
I published the successor in the README, which uses jaque inside.
So the project continues [here](https://github.com/streamx-co/ExTree), under AGPL though.

It would be interesting to know what isn't covered by the project.
Thanks in advance.

**Comment by Dan6667** [comment]
Thanks for reply!
1) What about features isn't covered in the project (this is propably a bug, but i'm not sure, still investigating this issue). E.g. following code:
`        SerializableConsumer<TestEntity> consumer = t -> t.setName("name");
        LambdaExpression<SerializableConsumer<TestEntity>> lambda = LambdaExpression.parse(consumer);`
Result in error: _java.lang.IllegalArgumentException: Not a lambda expression. Opcode RETURN is illegal._
For some reason it treats RETURN opcode as illegal.
Another example:
`        SerializablePredicate<TestEntity> predicate = t -> {
            t.getName();
            return true;
        };
        LambdaExpression<SerializablePredicate<TestEntity>> lambda = LambdaExpression.parse(predicate);`
Results in: java.lang.IllegalArgumentException: Not a lambda expression. Opcode POP is illegal.
And the last:
`        SerializablePredicate<TestEntity> predicate = t -> {
            t.setName("sd");
            return true;
        };
        LambdaExpression<SerializablePredicate<TestEntity>> lambda = LambdaExpression.parse(predicate);`
Error: java.lang.AssertionError

Environment:
Jaque version 2.4.4
Oracle JDK 1.8.0_241
Windows 10 Build 19041

2) Our team decided to make library that provides short and simple API to manipulate data from different data sources.
Lambdas are most likely the best solution for it. Putting it shortly, you write single lambda and then it's translated in native query of target data source.
To start, I decided to transate lambdas to Criteria Query, and I found visitor pattern not very convenient in my particular case. E.g. in some places I want to pass additional params, which is not allowed by interface.
I was sceptical about idea behind that library, but I made some progress and now think it's achievable.

Thanks for the link to repo, I'll check it.

**Comment by kostat** [comment]
1. The samples you provide should be working in the new library. In JaQue I
followed MS LINQ definition of lambda, so the cases you provide are
illegal. (try it in c# with their Expression). The new library removes this
limitation.
2. The "stronger" projects implement the whole SQL in Java. To some extent
it's something that you try to achieve. Or potentially you set even higher
:-). I could do all I need using visitor pattern.

In any case, be aware that the library is licenced AGPL in case you intend
to use it in commercial applications.

Kosta

**Comment by Dan6667** [comment]
Ok, thanks for the reply!
AGPL license seems a little bit tricky, I'll ask permission to use such libraries.
Our project already supposed to be opensource, so there is no problem.
But it will be used in other company commercial products (custom development), but since they do not involve distribution of code, seems like license is not triggered. I'll read more on this.
