### ISSUE TITLE
Do not work with Oracle OpenJDK(version 1.8.0_40)

### ISSUE THREAD

**Issue by DavidChild** [TrigerSoft/jaque#41]
hello, i use the jaque
( the version is 2.4.4) for my framwork.
Some machines are running normally, but my colleague's machine reported an error when using my class library. The tracking stack information  as follows:
![db64be85a60db220406454b89dd2bd7a](https://github.com/TrigerSoft/jaque/assets/18735238/4421bdeb-3be0-42fe-9561-9a1dec096d2c)

I think there may be compatibility  with the JDK version. If so, have you ever fixed this issue on your end?

**Comment by kostat** [comment]
Hello @DavidChild , you are absolutely right - JaQue does not support recent Java releases.
In fact this project is discontinued and migrated to https://github.com/streamx-co/ExTree, which supports the most recent Java releases.
The interfaces didn't change, only the packages, so migration should be straight forward.

**Comment by DavidChild** [comment]
> Hello @DavidChild , you are absolutely right - JaQue does not support recent Java releases. In fact this project is discontinued and migrated to https://github.com/streamx-co/ExTree, which supports the most recent Java releases. The interfaces didn't change, only the packages, so migration should be straight forward.

ok,tks @kostat ,I replaced jaque with extree witch repo is  https://github.com/streamx-co/ExTree, all is ok. tks.
